area_bedroom:
  module: InputSelect
  class: InputSelect
  dependencies: utils

  # Entity
  entity: input_select.area_bedroom

  # Automation Boolean
  automation_boolean: input_boolean.automation_area_bedroom

  # Triggers
  triggers:
    - entity: binary_sensor.motion_living_room
      state: "on"
      set_state: Night
      condition:
        - entity: input_select.area_bedroom
          expression: '!= "Disabled"'
        - entity: sensor.lux_motion_living_room
          expression: "< 10"
    - entity: binary_sensor.motion_living_room
      state: "on"
      set_state: "Day"
      condition:
        - entity: input_select.area_bedroom
          expression: '!= "Disabled"'
        - entity: sensor.lux_motion_living_room
          expression: "> 10"
    - entity: sensor.lux_motion_living_room
      expression: "< 10"
      set_state: "Night"
      condition:
        - entity: input_select.area_bedroom
          expression: '!= "Disabled"'
    - event: switch_bed_right_bedroom
      state: 4000
      set_state: "Disabled"

  # States
  states:
    Night:
      - entity: light.group_bedroom
        state: "on"
        brightness: 75
      - entity: switch.air_purifier_bedroom
        state: "on"
    Idle:
      - entity: light.group_bedroom
        state: "off"
        transition: 10
      - entity: switch.air_purifier_bedroom
        state: "off"
    Disabled:
      - entity: light.group_bedroom
        state: "off"
      - entity: switch.air_purifier_bedroom
        state: "off"
    Day:
      - entity: cover.curtains_bedroom
        state: 100
      - entity: light.group_bedroom
        state: "off"
      - entity: switch.air_purifier_bedroom
        state: "on"
