area_home:
  module: InputSelect
  class: InputSelect

  # Entity
  entity: input_select.area_home

  # Triggers
  triggers:
    # Lucas
    - entity: input_select.person_lucas
      state: Home
      set_state: Home
    - entity: input_select.person_lucas
      state: Away
      set_state: Away
    - entity: input_select.person_lucas
      state: Sleeping
      set_state: Sleeping
    - entity: input_select.person_lucas
      state: Awake
      set_state: Awake

  # States
  states:
    Home:
      - entity: input_select.area_kitchen
        state: Idle
      - entity: input_select.area_toilet
        state: Idle
      - entity: input_select.area_bathroom
        state: Idle
      - entity: input_select.area_bedroom
        state: Day
        condition:
          - entity: sensor.lux_motion_living_room
            expression: "> 10"
      - entity: input_select.area_bedroom
        state: Night
        condition:
          - entity: sensor.lux_motion_living_room
            expression: "<= 10"
      - entity: input_select.area_living_room
        state: Day
        condition:
          - entity: sensor.lux_motion_living_room
            expression: "> 10"
      - entity: input_select.area_living_room
        state: Night
        condition:
          - entity: sensor.lux_motion_living_room
            expression: "<= 10"
      - entity: input_select.area_hallway
        state: Idle
    Away:
      - entity: input_select.area_kitchen
        state: Disabled
      - entity: input_select.area_toilet
        state: Disabled
      - entity: input_select.area_bathroom
        state: Disabled
      - entity: input_select.area_bedroom
        state: Disabled
      - entity: input_select.area_living_room
        state: Disabled
      - entity: input_select.area_hallway
        state: Idle
    Sleeping:
      - entity: input_select.area_kitchen
        state: Disabled
      - entity: input_select.area_toilet
        state: Idle
      - entity: input_select.area_bathroom
        state: Idle
      - entity: input_select.area_bedroom
        state: Disabled
      - entity: input_select.area_living_room
        state: Disabled
      - entity: input_select.area_hallway
        state: Idle
      - entity: light.mirror_bathroom
        state: "off"
      - entity: input_select.animal_luna
        state: "Sleeping"
      - entity: input_select.animal_iera
        state: "Sleeping"
      - entity: input_select.animal_pluis
        state: "Sleeping"
      - entity: climate.softwarethermostat
        state: 20
    Awake:
      - entity: input_select.area_kitchen
        state: Idle
      - entity: input_select.area_toilet
        state: Idle
      - entity: input_select.area_bathroom
        state: Idle
      - entity: input_select.area_bedroom
        state: Day
      - entity: input_select.area_living_room
        state: Day
      - entity: input_select.area_hallway
        state: Idle
      - entity: input_select.animal_luna
        state: "Home"
      - entity: input_select.animal_iera
        state: "Home"
      - entity: input_select.animal_pluis
        state: "Home"
    Heating:
      - entity: climate.softwarethermostat
        state: 22
    Cooling:
      - entity: climate.softwarethermostat
        state: 20
