area_toilet:
  module: InputSelect
  class: InputSelect
  dependencies: utils

  # Timeout
  timeout:
    Occupied: 300
    Sleeping: 300

  # Entity
  entity: input_select.area_toilet

  # Automation Boolean
  automation_boolean: input_boolean.automation_area_toilet

  # Triggers
  triggers:
    - entity: binary_sensor.motion_toilet
      state: "on"
      set_state: "Occupied"
      condition:
        - entity: input_select.area_toilet
          expression: '!= "Disabled"'
        - entity: input_select.person_lucas
          expression: '!= "Sleeping"'
    - entity: binary_sensor.motion_toilet
      state: "on"
      set_state: "Sleeping"
      condition:
        - entity: input_select.person_lucas
          state: "Sleeping"

  # States
  states:
    Occupied:
      - entity: light.group_toilet
        state: "on"
        brightness: 75
    Idle:
      - entity: light.group_toilet
        state: "off"
        transition: 10
    Disabled:
      - entity: light.group_toilet
        state: "off"
    Sleeping:
      - entity: light.group_toilet
        state: "on"
        brightness: 1
