notification_animal_aikana:
  module: Animal
  class: Animal
  animal: Aikana
  humidity_entity: sensor.climate_humidity_aikana
  triggers:
    - humidity_high: 99
      humidity_low: 75
      notify:
        - mobile_app_phone_lucas
        - mobile_app_phone_elisa