animal_amduat:
  module: InputSelect
  class: InputSelect
  dependencies: utils

  # Entity
  entity: input_select.animal_amduat

  # Triggers
  triggers:
    - entity: sensor.climate_temperature_amduat
      expression: "> 28"
      set_state: Cooling
      condition:
        - entity: input_select.animal_amduat
          expression: '!= "Sleeping"'
    - entity: sensor.climate_temperature_amduat
      expression: "< 28"
      set_state: Heating
      condition:
        - entity: input_select.animal_amduat
          expression: '!= "Sleeping"'
    - time: "09:00:00"
      set_state: Heating
    - time: "23:00:00"
      set_state: Sleeping

  # States
  states:
    Cooling:
      - entity: light.terrarium_amduat
        state: "on"
        brightness: 25
        transition: 30
    Heating:
      - entity: light.terrarium_amduat
        state: "on"
        brightness: 75
        transition: 30
    Sleeping:
      - entity: light.terrarium_amduat
        state: "off"
        transition: 30
