animal_ghost:
  module: InputSelect
  class: InputSelect
  dependencies: utils

  # Entity
  entity: input_select.animal_ghost

  # Triggers
  triggers:
    - entity: sensor.climate_temperature_ghost
      expression: "> 28"
      set_state: Cooling
      condition:
        - entity: input_select.animal_ghost
          expression: '!= "Sleeping"'
    - entity: sensor.climate_temperature_ghost
      expression: "< 28"
      set_state: Heating
      condition:
        - entity: input_select.animal_ghost
          expression: '!= "Sleeping"'
    - time: "09:00:00"
      set_state: Heating
    - time: "23:00:00"
      set_state: Sleeping

  # States
  states:
    Cooling:
      - entity: light.terrarium_ghost
        state: "on"
        brightness: 25
    Heating:
      - entity: light.terrarium_ghost
        state: "on"
        brightness: 75
    Sleeping:
      - entity: light.terrarium_ghost
        state: "off"
